// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package foo

import (
	"github.com/jun06t/go-sample/wire/packages/model"
)

// Injectors from wire.go:

func initializeFooBarBaz() int {
	foo := model.ProvideFoo()
	bar := model.ProvideBar()
	baz := model.ProvideBaz()
	int2 := model.NewFooBarBaz(foo, bar, baz)
	return int2
}
