// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package foo

// Injectors from wire.go:

func initializeBarBaz() int {
	foo := ProvideFoo()
	bar := ProvideBar(foo)
	baz := ProvideBaz(foo)
	int2 := NewBarBaz(bar, baz)
	return int2
}
