// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package foo

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func initializeFooBarBaz() *FooBarBaz {
	foo := ProvideFoo()
	bar := ProvideBar()
	fooBarBaz := &FooBarBaz{
		MyFoo: foo,
		MyBar: bar,
	}
	return fooBarBaz
}

// wire.go:

var Set = wire.NewSet(
	ProvideFoo,
	ProvideBar,
	ProvideBaz, wire.Struct(new(FooBarBaz), "MyFoo", "MyBar"),
)
